const MESSAGE_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

const TRACE_EVENTS = {
  PUBLISHED: 'PUBLISHED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  MOVED_TO_DLQ: 'MOVED_TO_DLQ',
  REPLAYED: 'REPLAYED',
  LOCK_RECOVERED: 'LOCK_RECOVERED'
};

module.exports = { MESSAGE_STATUS, TRACE_EVENTS };
